# Generated by Django 4.0.3 on 2022-03-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedPokemon',
        ),
    ]
