# Generated by Django 4.0.3 on 2022-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_delete_capturedpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
