# Generated by Django 4.0.3 on 2022-03-28 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemon_captured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedpokemon',
            name='user',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
